name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      # Tên người dùng có thể tự đặt
      artifact-name:
        description: The name of the artifact
        required: false
        default: dist
        type: string
    outputs:
      # Tên tự chọn
      result:
        description: The result of the deployment operation
        value: ${{ jobs.deploy.outputs.outcome }}
    # secrets:
    #   some-secret:
    #     required: false
jobs:
  deploy:
    # Outputs: lưu các biến trong outputs để sử dụng cho outpus ở trên
    outputs:
      # Lấy output của step-result trong steps của id set-result
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Output Information
        run: echo "Deploying and uploading"
      - name: Set result output
        id: set-result
        run: echo 'step-result=success' >> $GITHUB_OUTPUT